name: Build & Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Сборка CFE
    uses: ShadobaAI/kafka-tools/.github/workflows/build.yml@main
    with:
      name_suffix: tester
      dockerhub_image: ${{ vars.DOCKERHUB_IMAGE }}
